### ISSUE TITLE
Route `/v1/shows/{id}` requires market query parameter but `get_a_show` market parameter is `Option`

### ISSUE THREAD

**Issue by oSumAtrIX** [ramsayleung/rspotify#442]
Spotify [documents](https://developer.spotify.com/documentation/web-api/reference/get-a-show) that the route `/v1/shows/{id}` **requires** a market query parameter but `get_a_show` market parameter is `Option`. If `None` is supplied, the request will fail with status code `404` as documented.

**Comment by ramsayleung** [comment]
The document doesn't mark the `market` parameter as `required`.

> If None is supplied, the request will fail with status code 404 as documented

From the document, it's by design:

> Note: If neither market or user country are provided, the content is considered unavailable for the client.
Users can view the country that is associated with their account in the [account settings](https://www.spotify.com/se/account/overview/).

I could remove the option field, and mark the market as `required`

**Comment by oSumAtrIX** [comment]
I understand where you are coming from. The documentation indeed treats it as optional, thus the implementation reflects the correct design.
