### ISSUE TITLE
Add support for `async/await`

### ISSUE THREAD

**Issue by echoSayonara** [ramsayleung/rspotify#78]
I tried to add support for `async/await` in my [branch](https://github.com/echoSayonara/rspotify/tree/support-for-async-await). I added an example (`examples/async-artist-top-tracks`) for it and went well.

If you have no future or ongoing plans to add support for `async/await`, please try my branch and leave me feedback.

**Comment by ramsayleung** [comment]
As for ongoing plan to support `async/await`, I have talked with the author of `spotify-tui` on this [PR](https://github.com/ramsayleung/rspotify/pull/72), and everything is working in process now. Because my full time job is so damn busy, I have to take some extra time to support `async/await`, so please be patient :)

**Comment by echoSayonara** [comment]
Sorry, i did not mean to rush you.
Understood. I'm looking forward to it. I would like to be helpful for it if I can.

**Comment by ramsayleung** [comment]
I think your work/branch is inspired, there are a lot of things I could learn from your work. I just push my WIP work to [remote origin](https://github.com/ramsayleung/rspotify/tree/ramsay/support-for-async-await). Instead of creating a `nonblocking` package, I prefer to create a `blocking` package, and make `nonblocking` default.

**Comment by ramsayleung** [comment]
> I would like to be helpful for it if I can.

If you have time, you could help me to convert those endpoint functions to `async/await` version, I just update the internal functions to `async`, there are still a lot of endpoint functions that needs to update.
https://github.com/ramsayleung/rspotify/blob/2ed470567990e0c2241e88db9c79afc5566f9b01/src/spotify/client.rs#L172
 https://github.com/ramsayleung/rspotify/blob/2ed470567990e0c2241e88db9c79afc5566f9b01/src/spotify/client.rs#L207

**Comment by echoSayonara** [comment]
will do.

**Comment by ramsayleung** [comment]
I just submit all the work `Rspotify` needs to do to support `async/await`, if you have time to join me, feel free to check it [The workload of adding support for `async/await`](https://github.com/ramsayleung/rspotify/issues/79)

**Comment by echoSayonara** [comment]
I started to modify endpoint functions to support `async/await ` in `client.rs`. I will send PR when i finished to implement them. Please wait.

**Comment by ramsayleung** [comment]
Perhaps you could send a new PR once you have finished to implement a endpoint function, or you could mark which endpoint function you are going to modify? just in case of any conflicting situation that we are both modifying the same endpoint function.

**Comment by echoSayonara** [comment]
oh, it has already been implemented.

**Comment by ramsayleung** [comment]
Rspotify has come to `async/await`, it's done.
