### ISSUE TITLE
Disable token caching

### ISSUE THREAD

**Issue by raffomania** [ramsayleung/rspotify#96]
I'm writing a web app for multiple users and would like to save the API token in my database. Is there a way to prevent `.spotify_token_cache.json` from being created?

**Comment by ramsayleung** [comment]
> Is there a way to prevent `.spotify_token_cache.json` from being created?

`.spotify_token_cache.json` is the default way to cache the token, there is no way to prevent to create `.spotify_token_cache.json` now :(

**Comment by raffomania** [comment]
that option would be awesome!

**Comment by ramsayleung** [comment]
I have completed this feature by adding two separate functions to get access token and refresh token without saving token into `cache_path` instead of adding a new option to disable cache. I think the current choice leads to less change of the library. If you want to know how to use the two new functions, check this example for more details :)
https://github.com/ramsayleung/rspotify/blob/92984d2bccaa9d9170f5b7962f1dcc2411b43212/examples/get_access_token_without_cache.rs#L22

https://github.com/ramsayleung/rspotify/blob/92984d2bccaa9d9170f5b7962f1dcc2411b43212/examples/get_access_token_without_cache.rs#L43

**Comment by raffomania** [comment]
alright, seems like a larger API surface, but it solves my problem so I'm happy :)
Thanks a lot for making this crate and for the quick reply! <3

**Comment by ramsayleung** [comment]
Thanks for your response, I am going to close this issue :)
